// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(SubscriberContext))]
    [Migration("20191020154315_changeRequired")]
    partial class changeRequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.Subscriber", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("family")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phone1")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phone2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phone3")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pobox")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Subscriber");
                });
#pragma warning restore 612, 618
        }
    }
}
